language: php
php:
  - 5.6
  - 7
  - 7.1
  - 7.2
cache:
  directories:
    - vendor
env:
  matrix:
    - COMPOSER_PREFER="--prefer-stable"
    - COMPOSER_PREFER="--prefer-lowest"
sudo: false
script:
  - make tests
